### ISSUE TITLE
isnt it FLAG_IMMUTABLE ?

### ISSUE THREAD

**Issue by millie-molly** [pichillilorenzo/flutter_inappwebview#1149]
A latest version of this package has a big problem with FLAG_MUTABLE.

error: cannot find symbol
              this, actionSourceId, actionIntent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_MUTABLE);
                                                                                          ^
  symbol:   variable FLAG_MUTABLE
  location: class PendingIntent

   if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
      return PendingIntent.getBroadcast(
              this, actionSourceId, actionIntent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_MUTABLE);
    } else {
      return PendingIntent.getBroadcast(
              this, actionSourceId, actionIntent, PendingIntent.FLAG_UPDATE_CURRENT);
    }
  }

**Comment by pichillilorenzo** [comment]
I can build without any problem using latest version.
I'm using [PendingIntent.FLAG_MUTABLE](https://developer.android.com/reference/android/app/PendingIntent#FLAG_MUTABLE) (Added in API level 31) because otherwise, the `ActionBroadcastReceiver` will not be called on Android.
Try to clean and build again your project. Or maybe setting in your `build.gradle` the `compileSdkVersion` to `31`

**Comment by phanthelam** [comment]
I'm facing same problem.any solution ? @millie-molly

**Comment by Aqua-Ye** [comment]
I had the same issue, and updated `buildToolsVersion` to fix it.
