### ISSUE TITLE
setActionButton missing

### ISSUE THREAD

**Issue by rickyoleary** [pichillilorenzo/flutter_inappwebview#1152]
As part of https://developer.chrome.com/docs/android/custom-tabs/integration-guide/

Specifically: https://developer.chrome.com/docs/android/custom-tabs/integration-guide/#configure-a-custom-action-button

We should be able to set an action button using `ChromeSafariBrowser`. But currently only `addMenuItem `is possible using the builder.

**Comment by ycv005** [comment]
@pichillilorenzo  while using the setActionButton, I have used an sharing image, but instead of showing on top toolbar, it is showing at the bottom. Is this a bug or image size issue ?

Here is the size of the image used- 
<img width="129" alt="Screenshot 2022-12-04 at 5 56 00 PM" src="https://user-images.githubusercontent.com/26734819/205490306-64df366b-7047-4b8b-8a51-a799413d09a7.png">


Here is the preview
<img width="359" alt="Screenshot 2022-12-04 at 5 54 07 PM" src="https://user-images.githubusercontent.com/26734819/205490230-91623779-4d52-4dbe-b3b7-9caf1a59d217.png">

**Comment by ycv005** [comment]
@pichillilorenzo Also, the override method `onClick`, not working. I want to add an shareUrl method using a [share package](https://pub.dev/packages/share_plus).
```
onClick: (url, title) async {
            print("here custome set action button click- $url");
           await shareUrl(
                url.toString(), "url", "tbo_chrome_action", "tbo", context);
          }
```

**Comment by ycv005** [comment]
@rickyoleary did you face the same ? if not, let me what size of image & type of image you used, also what code you wrote. Thanks in advance.
