### ISSUE TITLE
ChromeSafariBrowser reloads when app is minimized and reopened

### ISSUE THREAD

**Issue by rickyoleary** [pichillilorenzo/flutter_inappwebview#1195]
[As per the example here](https://inappwebview.dev/docs/chrome-safari-browser/basic-usage/), if changed to say Google and you do a search then minimize the app and reopen it (without closing the app) the widget reloads (so displays the Google homepage again).

I'm not registering this as a bug as I'm not sure if it's expected behaviour. If it is, does anyone know how to persist the page so it doesn't reload once reopened after minimizing?

I am testing on Samsung A52G, Android 12. One UI version 4.1.

I have tried **keepAliveEnabled** as true, but it didn't make any difference (not sure if it should).

**Comment by rickyoleary** [comment]
This only seems to happen when the phone is connected via USB. If I disconnect the cable and replicate the steps (minimize, reopen) it's fine!?

**Comment by DanLux** [comment]
Not sure if related, but I am currently facing a similar issue. But instead of reloading the page, whenever I minimize, reopen and then close the ChromeSafariBrowser, I cannot get back to my main application. In fact, it becomes unusable from then on. 

When my app goes to background with ChromeSafariBrowser open, I always get log the message
> detachFromRenderer() invoked when no FlutterRenderer was attached.

And when I try to close the browser, I get the log message:
> Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.pichillilorenzo/flutter_chromesafaribrowser_[ID]

This only happens on Android.
