### ISSUE TITLE
How to upgrade connections to https

### ISSUE THREAD

**Issue by DennisMuchiri** [pichillilorenzo/flutter_inappwebview#1218]
Hi @pichillilorenzo  thanks for this awesome package. My question would be how to upgrade HTTPS connections. I realized some sites using https require this option to be turned on to be able to get the page. Example under shields in brave browser :
<img width="690" alt="Screenshot 2022-06-10 at 11 55 30" src="https://user-images.githubusercontent.com/11217100/173030385-f75e5e8b-fc24-450d-96ff-5260fec1df7b.png">

**Comment by DennisMuchiri** [comment]
Yes I have searched about this problem

**Comment by DennisMuchiri** [comment]
@crazecoder @AlexV525 @cbodin @matthewlloyd  @robsonmeemo  @ryanhz @carloserazo47 Please help

**Comment by ryanhz** [comment]
I switch to the official webview_flutter long time ago.

"Upgrade connections to HTTPS" means Brave will try to connect over HTTPS and ignore HTTP when possible.
So I think this has nothing to do with this plugin.  Check if the URL you try to load is started with http:// instead of https://
If so, change it to https://
