### ISSUE TITLE
Execution failed for task ':app:mergeDexProdRelease'.

### ISSUE THREAD

**Issue by j-j-gajjar** [pichillilorenzo/flutter_inappwebview#1275]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  3.0.1              |
| Plugin version       |      -         |
| Android version      |        -       |
| iOS version          |          -     |
| Xcode version        |        -       |

## Description
when I try to create a build using android flavor then it failed and gives this error.

##  Error

```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexProdRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Type com.pichillilorenzo.flutter_inappwebview.BuildConfig is defined multiple times: /home/user/Documents/Flutter_Projects/myproject/build/flutter_inappwebview_quill/.transforms/178f333172fee0932eea9714e74812c6/classes/classes.dex, /home/user/Documents/Flutter_Projects/myproject/build/flutter_inappwebview/.transforms/66f9bac8836a8f0fbfe12bfeaeaef088/classes/classes.dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 41s

**Comment by ngc1514** [comment]
Had the same error. I had flutter_quill inside my pubspec.yaml. Removing it fixed the problem. I'm guessing it's due to flutter_inappwebview_quill conflicting with flutter_inappwebview.

**Comment by konnic** [comment]
I'm currently facing the same issue, but removing `flutter_quill` from my dependencies is unfortunately not an option for me. @ngc1514 I agree that the issue lies with [flutter_inappwebview_quill](https://github.com/garv-shah/flutter_inappwebview), which uses the exact same package name (com.pichillilorenzo.flutter_inappwebview) as the original `flutter_inappwebview` package.
@garv-shah would it be possible to change the `flutter_inappwebview_quill` package name so that it doesn't collide with the original package?

**Comment by garv-shah** [comment]
hi there! I've updated my repository with the name change, but seeing as [flutter_quill_extensions](https://pub.dev/packages/flutter_quill_extensions) doesn't have a GitHub repository anywhere, I'm not sure how to get that change to be updated on Flutter Quill itself.

Seeing as how `flutter_inappwebview` has had a major refactor since when I made the package, I think it would probably make more sense get Flutter Quill to depend on the official repository itself

**Comment by konnic** [comment]
@garv-shah thanks a lot for the quick package name change! I'll try to get in touch with the maintainers of flutter_quill_extensions and flutter_quill.

> Seeing as how flutter_inappwebview has had a major refactor since when I made the package, I think it would probably make more sense get Flutter Quill to depend on the official repository itself
Does that mean that you didn't do any changes specifically for quill in your fork? If so, I totally agree.

**Comment by garv-shah** [comment]
> Does that mean that you didn't do any changes specifically for quill in your fork?

Yup, exactly, it was merely a fix for a bug that this repository had with the Xcode 14/iOS 16 betas that prevented building which got fixed officially in [this PR](https://github.com/pichillilorenzo/flutter_inappwebview/pull/1238), and was meant to be temporary since it was blocking app building on the latest iOS version. 

Here's the exact issue: https://github.com/singerdmx/flutter-quill/pull/883

Either way, it was just meant to be a temporary change since as predicted it took about 4 months for it to be fixed officially, so it's definitely long overdue a change back :D

**Comment by konnic** [comment]
@garv-shah thanks a lot for the clarification! 🙏
