### ISSUE TITLE
Print preview is not working?

### ISSUE THREAD

**Issue by onlinecheckwriter** [pichillilorenzo/flutter_inappwebview#128]
Hello?
window.print();
Should popup the printer dialogue, but it is not coming?
is there any solution for that?

**Comment by pichillilorenzo** [comment]
Fix available starting from the version `3.0.0`.

**Comment by alexmik95** [comment]
hello guys, sorry to post in a closed issue but seems to not be resolved yet. I'm on version `3.1.0` and calling `_webviewController.printCurrentPage()` and `_webviewController.evaluatejavascript(source: "window.print()")` raises exception. As you can see in the [console log](https://pastebin.com/aFV9ybin) it can't print because not in an Activity. Am I doing something wrong or hasn't it been fixed yet?

**Comment by pichillilorenzo** [comment]
@alexmik95 Fix will be available in the next release `3.3.0`!

**Comment by pichillilorenzo** [comment]
New version `3.3.0` released!
