### ISSUE TITLE
Disable sharing url link in ChromeSafariBrowser

### ISSUE THREAD

**Issue by nicolo-fr** [pichillilorenzo/flutter_inappwebview#1301]
## Environment

**Flutter version:** 
**Plugin version:**    
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description

**What you'd like to happen:** 
At the moment, a url launched in a ChromeSafariBrowser is sharable : on Android, the user can share the link by clicking on the more_vertical icon (even if the share is set to shareState: CustomTabsShareState.SHARE_STATE_OFF), on iOS, the user can tap the share bottom in toolBarBottom.
It would be nice to be able to disable the sharing capability in ChromeSafariBrowser. If your URL display a machanism to control the ID of your user, you may not want the user to be able share that link with anybody else. 

**Alternatives you've considered:**   
On iOS, one option would be to have hideToolbarBottom option similar to the one found in InAppBrowser

**Images:**

**Comment by ycv005** [comment]
@pichillilorenzo How we can override chromesafaribrowser share method so that, when ever sharing button is tap, we can modify it. Or if this is not possible then can we have floating button inside chromesafaribrowser. 
Reason why I am asking this feature is because whenever use share url, and other person open it, the url don't app in our app but open in the browser.
