### ISSUE TITLE
If the application is killed while Foreground service is running, it gets an error

### ISSUE THREAD

**Issue by 1garipdeveloper** [pichillilorenzo/flutter_inappwebview#1316]
I have a service that works in the foreground. When I kill the application, innappwebview crashes the application. When the application crashes, my foreground service shuts down.  
Device : Xiaomi Not 9 Pro

E/chromium(16393): [ERROR:aw_browser_terminator.cc(156)] Renderer process (16589) crash detected (code -1).
E/chromium(16393): [ERROR:aw_browser_terminator.cc(112)] Render process (16589) kill (OOM or update) wasn't handed by all associated webviews, killing application.

How can I solve the problem

- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      3.0.5       |
| Plugin version       |   5.4.3+7     |
| Android version      |       2021.2      |
| iOS version          |               |
| Xcode version        |     13.4.1          |

Device information: 

## Description

**Expected behavior:** 

**Current behavior:** 

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by 1garipdeveloper** [comment]
The problem still continues. Android webview has the same problem.
There is no such problem in webview_flutter.

**Comment by jaroslawdabrowski** [comment]
I am experiencing similar issues on my Xiaomi Redmi Note 11 phone. It wasn't the case 1 month ago. It started to appear in January, perhaps this is because of the phone update that I did? It happens when I pause the app and then open it again. 

I/flutter (16699): │ 💡 [WebView State] Status change to: AppLifecycleState.paused
W/cr_ChildProcessConn(16699): onServiceDisconnected (crash or killed by oom): pid=16781 bindings:W  S
E/chromium(16699): [ERROR:aw_browser_terminator.cc(156)] Renderer process (16781) crash detected (code -1).
[InAppWebViewController] (android) WebView ID 0 calling "onRenderProcessGone" using {didCrash: false, rendererPriorityAtExit: 2}

**Comment by huubao2309** [comment]
> I am experiencing similar issues on my Xiaomi Redmi Note 11 phone. It wasn't the case 1 month ago. It started to appear in January, perhaps this is because of the phone update that I did? It happens when I pause the app and then open it again.
> 
> I/flutter (16699): │ 💡 [WebView State] Status change to: AppLifecycleState.paused W/cr_ChildProcessConn(16699): onServiceDisconnected (crash or killed by oom): pid=16781 bindings:W S E/chromium(16699): [ERROR:aw_browser_terminator.cc(156)] Renderer process (16781) crash detected (code -1). [InAppWebViewController] (android) WebView ID 0 calling "onRenderProcessGone" using {didCrash: false, rendererPriorityAtExit: 2}

Hi @jaroslawdabrowski, I had the same problem on Xiaomi Redmi Note 11 phone. Have you solved this problem yet?
