### ISSUE TITLE
ios 14.5 crash reports upgradeKnownHostsToHTTPS

### ISSUE THREAD

**Issue by nne998** [pichillilorenzo/flutter_inappwebview#1393]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      3.3.0         |
| Plugin version       |       6.0.0-beta2        |
| Android version      |      12        |
| iOS version          |      15.7         |
| Xcode version        |      14.0         |

## Description

Many uses reported app crashed,  when my app creating a webview window,  but i can't reproduce it.

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/148901/197444892-bbe15991-163a-4719-b5af-12f648f0f8ce.png">

ios crash reports when create webview
[2022-10-24_00-33-18.8309_+0800-c2bffc0a5095c9dd59487af39c5db938bdaac58b.crash.zip](https://github.com/pichillilorenzo/flutter_inappwebview/files/9848636/2022-10-24_00-33-18.8309_%2B0800-c2bffc0a5095c9dd59487af39c5db938bdaac58b.crash.zip)

**Comment by pichillilorenzo** [comment]
Thanks for the report!

From the crash report, it is caused by the `upgradeKnownHostsToHTTPS` property on iOS 14.5, which should be already available from 14.5+ (official iOS docs [here](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/3752243-upgradeknownhoststohttps)), but for some strange reason, it is not.

So I will bump the native version check for that property to 15.0+.

**Comment by pichillilorenzo** [comment]
Released new version `6.0.0-beta.8` with the fix
