### ISSUE TITLE
Only Load a part of a website eg. <div id = "info">

### ISSUE THREAD

**Issue by YohanWadia** [pichillilorenzo/flutter_inappwebview#1404]
## Environment

**Flutter version:** 3.3.5
**Plugin version:** 6.x.x   
**Android version:**    
**iOS version:**
**Xcode version:**  
**Device information:**    

## Description
Im working in Flutter Web and the InAppWebView works fine.
But I tried loading a part of a website but failed.
I tried looking at the docs... but searches never revealed anything.

**What you'd like to happen:** 
I would like to be able to display only a part of a website... like may be a particular div tag... or may be just a para <p> with according to may be its Id or Class.

**Alternatives you've considered:**   
many... but now that im already working with InAppWebView was wondering could this be done? 

**Images:**

**Comment by pichillilorenzo** [comment]
You could do that using javascript code and removing or hiding the elements you want (for example using `evaluateJavascript`), but on Flutter Web that's not possible, as iframe is very limited.

**Comment by YohanWadia** [comment]
As the owner of the website i did try it... but it still displays.
heres my flutter piece
```
InAppWebView(
                    key: webViewKey,
                    initialUrlRequest: URLRequest( url: Uri.parse('https://candle-far-amaranthus.glitch.me/')),
                    onWebViewCreated: (controller) { webViewController = controller;
                      controller.evaluateJavascript(source: "document.getElementById('img1').style.display='none';");
                      },
```

and in my index.html i have this as one of the tags in the body

```
<div>
      <img id= "img1"
          src="https://somepathway to my/banner.jpg"          
          alt="BannerAd"
          
        />
    </div>
```

any hints on what i might have over seen?
thanks,
YOhan

**Comment by pichillilorenzo** [comment]
You are calling `evaluateJavascript` inside `onWebViewCreated`.

It won't work because that page isn't loaded and you can't execute javascript code with `evaluateJavascript` If the page isn't loaded yet. It's too early. You should call it in `onLoadStop`. Or you can try to use `UserScript` with `UserScriptInjectionTime. AT_DOCUMENT_START` ([User Script Official doc](https://inappwebview.dev/docs/webview/javascript/user-scripts)).

Please, read the docs before posting issues. Here is the doc reference [InAppWebViewController.evaluateJavascript](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/InAppWebViewController/evaluateJavascript.html).
