### ISSUE TITLE
Google Signin in the webpage not working

### ISSUE THREAD

**Issue by fathah** [pichillilorenzo/flutter_inappwebview#1438]
Hey,
I'm trying to implement a login feature in my app. For login, the user will be redirected to the webpage, and is done through ``. 
Unfortunately, it doesn't open Google Login.

Here's the code
```dart
  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
      crossPlatform: InAppWebViewOptions(
        useShouldOverrideUrlLoading: true,
        mediaPlaybackRequiresUserGesture: false,
      ),
      android: AndroidInAppWebViewOptions(
        useHybridComposition: true,
      ),
      ios: IOSInAppWebViewOptions(
        allowsInlineMediaPlayback: true,
      ));

// Build Method

InAppWebView(
        key: webViewKey,
        initialUrlRequest:
            URLRequest(url: Uri.parse("https://account.ziqx.in/")),
        initialOptions: options,
        onConsoleMessage: (controller, consoleMessage) {
          print("Console::$consoleMessage");
        },
      ),
```
Console Log:
```js
{message: Uncaught TypeError: Cannot read property 'requestAccessToken' of undefined, messageLevel: 3}
```

**Comment by fathah** [comment]
I still couldn't fix that. However, it works wit `ChromeSafariBrowser`.

**Comment by pichillilorenzo** [comment]
Google allows sign-in with Google Account only in normal browsers, it restricts it in web-views due to security reasons and recommends Google SDKs for iOS and Android for this purpose.

A similar behaviour exists for Facebook login.

In general, these services recognize the default WebView user agent, so to make it work, you could just set a custom user agent value.

I have created an example that works using `InAppWebView` here: https://github.com/pichillilorenzo/flutter_inappwebview_examples/tree/main/third_party_oauth_user_sign_in
