### ISSUE TITLE
[Android] Loss of Referer HTTP header when using shouldOverrideUrlLoading

### ISSUE THREAD

**Issue by andyduke** [pichillilorenzo/flutter_inappwebview#1450]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version | 3.3.9 |
| Plugin version  | 5.7.2 & 6.0.0-beta.19 |
| Android version | 10 |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

## Description

Currently, if you enable the `useShouldOverrideUrlLoading` option and use the `shouldOverrideUrlLoading` callback, **Android** WebView loses the referrer header. This is because `InAppWebViewClient.java` cancels the loading in the `shouldOverrideUrlLoading` method and sends the request through the `webView.loadUrl` method, which is passed the url and custom headers, but not the **referer** header.

As a workaround, you can append the "referer" header (if it is not already there) to the sent headers, equal to the current page address (maybe save it to a variable in `onPageStarted`) here: https://github.com/pichillilorenzo/flutter_inappwebview/blob/c2ce274754be06c879f3fe733e4429ec70be4e94/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/in_app_webview/InAppWebViewClient.java#L110-L119.

**Comment by pichillilorenzo** [comment]
Unfortunately, that's the only way to implement a navigation delegate on Android.

I can't set the Referer header on my own, not because it's not technically possible (that's easy using `WebView.getUrl()` and add it to the headers before the `webView.loadUrl(url, headers);` Java method call), but because the [Referrer-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) should be considered to set or not the correct `Referer` header value (also for security reasons!) for that request and, unfortunately, it's not available through the `WebResourceRequest.getRequestHeaders()`, so it cannot be "calculated".

So, currently, if you need the Referer header on Android, you should add it on your own, implementing the `InAppWebView.shouldOverrideUrlLoading` event, for example:
```dart
shouldOverrideUrlLoading: (controller, navigationAction) async {
  if (!kIsWeb &&
      defaultTargetPlatform == TargetPlatform.android &&
      navigationAction.isForMainFrame) {
    // only for Android
    final currentUrl = await controller.getUrl();
    if (currentUrl != null) {
      var headers = navigationAction.request.headers;
      headers ??= {};
      var hasRefererHeader = headers.keys
          .map((k) => k.toLowerCase())
          .contains('referer');
      if (!hasRefererHeader) {
        // use the full current URL (unsafe-url) or
        // create your own URL structure here based on a Referrer-Policy.
        headers['Referer'] = currentUrl.toString();
        navigationAction.request.headers = headers;
      }
    }
    controller.loadUrl(urlRequest: navigationAction.request);
    return NavigationActionPolicy.CANCEL;
  }

  return NavigationActionPolicy.ALLOW;
},
```

**Comment by ndilworth** [comment]
Hi @pichillilorenzo sorry to comment on a closed ticket but I tried your above sample code and on Android my navigationAction.request.headers are always null. On iOS they are populated correctly. I'm currently on v5.4.3+8 and have tried the latest v5.7.2+3 and have the same result. Is this a permission issue on my side?
