### ISSUE TITLE
Xiaomi store - Conflict of Privacy Permissions, android.permission.MY_READ_INSTALLED_PACKAGES

### ISSUE THREAD

**Issue by hellohejinyu** [pichillilorenzo/flutter_inappwebview#1462]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |    3.3.8           |
| Plugin version  |       [6.0.0-beta.21](https://pub.dev/packages/flutter_inappwebview/versions/6.0.0-beta.21)       |
| Android version |      10         |
| iOS version     |               |
| macOS version   |              |
| Xcode version   |               |

Device information:  xiaomi mix3

## Description

Thank you so much for developing this flutter library. Overall performance is better than `webview_flutter`. But I have a problem when submitting the app to the app market (Xiaomi App Store). They run a security scan on the application and check that the application gets the list of installed applications at startup (android.permission.MY_READ_INSTALLED_PACKAGES).

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/8766034/206426188-c3c8cc8a-72dc-4606-85bd-0a178529a3bc.png">

In Xiaomi's view, it is an act of disrespecting user privacy to perform such an operation before the user agrees to the application privacy policy. So they refuse to pass my app.

So I would like to ask if it is possible to let WebView be initialized when it is actually used, or provide a method for developers to initialize manually.

**Expected behavior:** 

Do not get the list of installed applications when the application starts

**Current behavior:** 

When the app starts, when the user has not agreed to the privacy policy, get the list of installed apps immediately

## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by hellohejinyu** [comment]
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1304

Actually this issue also describes this problem, but I guess this issue doesn't follow the issue template, and uses Chinese to describe the problem, so it doesn't get your attention.

**Comment by ZhangZhiH** [comment]
I'm facing the same problem right now because the Xiaomi store won't let me put it on the shelves

**Comment by hellohejinyu** [comment]
> I'm facing the same problem right now because the Xiaomi store won't let me put it on the shelves

https://github.com/shirne/flutter_inappwebview/tree/fix_init

You can see this buddy's fork version, delay initialization webview, I have passed Xiaomi's review.

**Comment by pichillilorenzo** [comment]
I don't have any `android.permission.MY_READ_INSTALLED_PACKAGES` in my android manifest file.
Just check it:
- version 6: https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/android/src/main/AndroidManifest.xml
- version 5: https://github.com/pichillilorenzo/flutter_inappwebview/blob/v5.7.2%2B2/android/src/main/AndroidManifest.xml

I don't see why the delay initialization should fix it. My plugin doesn't use it.

Maybe, is it related to https://github.com/pichillilorenzo/flutter_inappwebview/issues/1371 ?

**Comment by pichillilorenzo** [comment]
@hellohejinyu Ok, so the problem is related to the native classes that are requesting permissions to load, I think, the instances from the corresponding internal Provider of the system.
For example, to get the Cookie Manager instance on Android, the internal API is calling:
```java
    /**
     * Gets the singleton CookieManager instance.
     *
     * @return the singleton CookieManager instance
     */
    public static CookieManager getInstance() {
        return WebViewFactory.getProvider().getCookieManager();
    }
```

Didn't know about that because, well, it's an internal Android API.

I could implement something like @shirne has already done, but before doing that, I would like to try another way, using a "lazy" initialization for the Cookie Manager and the other classes.

Because this change could be a breaking change, maybe it could be available only starting from plugin version >= 6.

**Comment by AlexV525** [comment]
> I could implement something like @shirne has already done, but before doing that, I would like to try another way, using a "lazy" initialization for the Cookie Manager and the other classes.

We don't have to call `init` explicitly if the method is done when the first controller is constructing, using flags to indicate could be better IMO.

**Comment by ZhangZhiH** [comment]
I have solved the current problem through your means. Thank you very much @hellohejinyu

**Comment by pichillilorenzo** [comment]
Fixed with release `6.0.0-beta.22` and `5.7.2+3`

**Comment by pichillilorenzo** [comment]
You don't need to call any `init` method or whatever. The android classes will be initiated when you will call native methods the first time, such as `CookieManager.getCookie`, etc.

**Comment by matrixccp** [comment]
Our application was rejected in the OPPO application market. The reason is that the user installation list was illegally collected before agreeing to the privacy policy. The following is the stack information given by the oppo detection report.

Flutter version   3.7.3
Plugin version   5.7.2+3
Android version   Android 12

Stack trace:

{
"stackTrace": [{
"className": "libcore.util.Janus",
"level": 0,
"fileName": "Janus.java",
"methodName": "getData",
"lineNumber": 862
},
{
"className": "android.app.ApplicationPackageManager",
"level": 0,
"fileName": "ApplicationPackageManager.java",
"methodName": "getPackageInfoAsUser",
"lineNumber": 184
},
{
"className": "android.app.ApplicationPackageManager",
"level": 0,
"fileName": "ApplicationPackageManager.java",
"methodName": "getPackageInfo",
"lineNumber": 159
},
{
"className": "android.webkit.WebViewFactory",
"level": 0,
"fileName": "WebViewFactory.java",
"methodName": "getWebViewContextAndSetProvider",
"lineNumber": 392
},
{
"className": "android.webkit.WebViewFactory",
"level": 0,
"fileName": "WebViewFactory.java",
"methodName": "getProviderClass",
"lineNumber": 439
},
{
"className": "android.webkit.WebViewFactory",
"level": 0,
"fileName": "WebViewFactory.java",
"methodName": "getProvider",
"lineNumber": 251
},
{
"className": "android.webkit.WebView",
"level": 0,
"fileName": "WebView.java",
"methodName": "getFactory",
"lineNumber": 2546
},
{
"className": "android.webkit.WebView",
"level": 0,
"fileName": "WebView.java",
"methodName": "ensureProviderCreated",
"lineNumber": 2541
},
{
"className": "android.webkit.WebView",
"level": 0,
"fileName": "WebView.java",
"methodName": "setOverScrollMode",
"lineNumber": 2606
},
{
"className": "android.view.View",
"level": 0,
"fileName": "View.java",
"methodName": "",
"lineNumber": 4823
},
{
"className": "android.view.View",
"level": 0,
"fileName": "View.java",
"methodName": "",
"lineNumber": 4964
},
{
"className": "android.view.ViewGroup",
"level": 0,
"fileName": "ViewGroup.java",
"methodName": "",
"lineNumber": 659
},
{
"className": "android.widget.AbsoluteLayout",
"level": 0,
"fileName": "AbsoluteLayout.java",
"methodName": "",
"lineNumber": 55
},
{
"className": "android.webkit.WebView",
"level": 0,
"fileName": "WebView.java",
"methodName": "",
"lineNumber": 408
},
{
"className": "android.webkit.WebView",
"level": 0,
"fileName": "WebView.java",
"methodName": "",
"lineNumber": 353
},
{
"className": "android.webkit.WebView",
"level": 0,
"fileName": "WebView.java",
"methodName": "",
"lineNumber": 336
},
{
"className": "android.webkit.WebView",
"level": 0,
"fileName": "WebView.java",
"methodName": "",
"lineNumber": 323
},
{
"className": "android.webkit.WebView",
"level": 0,
"fileName": "WebView.java",
"methodName": "",
"lineNumber": 313
},
{
"className": "com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.InputAwareWebView",
"level": 0,
"fileName": "InputAwareWebView.java",
"methodName": "",
"lineNumber": 34
},
{
"className": "com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.InAppWebView",
"level": 0,
"fileName": "InAppWebView.java",
"methodName": "",
"lineNumber": 188
},
{
"className": "com.pichillilorenzo.flutter_inappwebview.webview.in_app_webview.FlutterWebView",
"level": 0,
"fileName": "FlutterWebView.java",
"methodName": "",
"lineNumber": 68
},
{
"className": "com.pichillilorenzo.flutter_inappwebview.FlutterWebViewFactory",
"level": 0,
"fileName": "FlutterWebViewFactory.java",
"methodName": "create",
"lineNumber": 44
},
{
"className": "io.flutter.plugin.platform.PlatformViewsController$1",
"level": 0,
"fileName": "PlatformViewsController.java",
"methodName": "createPlatformView",
"lineNumber": 503
},
{
"className": "io.flutter.plugin.platform.PlatformViewsController$1",
"level": 0,
"fileName": "PlatformViewsController.java",
"methodName": "createForPlatformViewLayer",
"lineNumber": 163
},
{
"className": "io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1",
"level": 0,
"fileName": "PlatformViewsChannel.java",
"methodName": "create",
"lineNumber": 105
},
{
"className": "io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1",
"level": 0,
"fileName": "PlatformViewsChannel.java",
"methodName": "onMethodCall",
"lineNumber": 55
},
{
"className": "io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler",
"level": 0,
"fileName": "MethodChannel.java",
"methodName": "onMessage",
"lineNumber": 258
},
{
"className": "io.flutter.embedding.engine.dart.DartMessenger",
"level": 0,
"fileName": "DartMessenger.java",
"methodName": "invokeHandler",
"lineNumber": 295
},
{
"className": "io.flutter.embedding.engine.dart.DartMessenger",
"level": 0,
"fileName": "DartMessenger.java",
"methodName": "lambda$dispatchMessageToQueue$0$DartMessenger",
"lineNumber": 322
},
{
"className": "io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0",
"level": 0,
"methodName": "run",
"lineNumber": 12
},
{
"className": "android.os.Handler",
"level": 0,
"fileName": "Handler.java",
"methodName": "handleCallback",
"lineNumber": 873
},
{
"className": "android.os.Handler",
"level": 0,
"fileName": "Handler.java",
"methodName": "dispatchMessage",
"lineNumber": 99
},
{
"className": "android.os.Looper",
"level": 0,
"fileName": "Looper.java",
"methodName": "loop",
"lineNumber": 193
},
{
"className": "android.app.ActivityThread",
"level": 0,
"fileName": "ActivityThread.java",
"methodName": "main",
"lineNumber": 6756
},
{
"className": "java.lang.reflect.Method",
"level": 0,
"fileName": "Method.java",
"methodName": "invoke",
"lineNumber": -2
},
{
"className": "com.android.internal.os.RuntimeInit$MethodAndArgsCaller",
"level": 0,
"fileName": "RuntimeInit.java",
"methodName": "run",
"lineNumber": 507
},
{
"className": "com.android.internal.os.ZygoteInit",
"level": 0,
"fileName": "ZygoteInit.java",
"methodName": "main",
"lineNumber": 863
}
],
"permission_group": "",
"params": {
"flags": 268444864,
"packageName": "com.android.webview",
"userId": 0
},
"result": {
  "PackageInfo": "PackageInfo{190b648 com.android.webview}"
},
  "permission_level": "",
  "stack_txt": 0
}
