### ISSUE TITLE
onLoadStart and onLoadStop return the initial url every time on WEB 

### ISSUE THREAD

**Issue by melihhakanpektas** [pichillilorenzo/flutter_inappwebview#1764]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version | 3.10.6 |
| Plugin version  | v6.0.0-beta.24+1 |

## Description

**Expected behavior: The url or controller parameters of onLoadStart return the CURRENT url on WEB.** 

**Current behavior: : The url or controller parameters of onLoadStart return the INITIAL url on WEB** 

## Steps to reproduce

```dart
InAppWebView(
                                initialUrlRequest: URLRequest(
                                  url: WebUri.uri(
                                    Uri.parse('https://www.google.com/'),
                                  ),
                                ),
                                onLoadStart: (controller, url) {
                                  print('onLoadStart $url'); // this returns initial url every time (and also works end of the load like onLoadStop), 
                                  if (url ==
                                      Uri.parse(
                                        'https://www.google.com/',
                                      )) {
                                    Navigator.pop(context, true); // this never works
                                  }
                                  if (url ==
                                      Uri.parse(
                                        'https://www.yandex.com/',
                                      )) {
                                    Navigator.pop(context, false); // this never works.
                                  }
                                },
                              )
```
2. Than I had load a diffrent url
3. Then print function return that: https://www.google.com/

**Comment by burakcbdn** [comment]
same here with initial html data

**Comment by pichillilorenzo** [comment]
That’s a limitation of Web platform using IFrame HTML elements unfortunately.
The problem is related on how iframes works and about their security (cross-origin errors).
If the url doesn’t have the same origin of the web page that is containing the IFrame, then most of the things would not work.
There is no workaround about that, it’s simply how the iframes work on browsers (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe).

A truly WebView doesn’t exist on Web platform (on Web you are, well, already on Web!).
The IFrame HTML element is just the HTML element that is the closest possible to have something similar, but it’s very limited.
To check if an event or a method is available and more info, see the API Reference for that.
