### ISSUE TITLE
await webViewController.getUrl() returns null after migration to HeadlessInAppWebView.

### ISSUE THREAD

**Issue by ylaptiev-sommo** [pichillilorenzo/flutter_inappwebview#1987]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |       3.16.5          |
| Plugin version        |       ^6.0.0        |
| Android version       |       14        |
| iOS version           |        17.2       |
| Xcode version         |       15.0        |

Device information: 
Google Pixel 7 Pro (Android 14)
iPhone SE(2022) (iOS 17.2)
## Description

**Expected behavior:** 
await webViewController.getUrl() returns URL of current page instead of null.
**Current behavior:** 
Page is fully loaded and displayed but await webViewController.getUrl() always returns null.
It causes one more issue: webViewController.evaluateJavascript('window.myWindowProperty.apply(...)') will return WKJavaScript exception with message 'undefined is not an object'
Note: everything works just fine if not using HeadlessInAppWebView
## Steps to reproduce

1. Define HeadlessInAppWebView, setup it in initState(), pass it to InAppWebView parameter in build() method.
2. print await webViewController.getUrl().
3. try to evaluate page specific js code.

## Screenshot
<img width="814" alt="Screenshot 2024-01-22 at 01 45 26" src="https://github.com/pichillilorenzo/flutter_inappwebview/assets/152600912/b201a6c6-c004-4af8-9ea8-8574e5cddd94">

**Comment by pichillilorenzo** [comment]
You need to call the `run` method and `await` it to be sure you have started the headless WebView.
The `initState` is not a good place to start it because you cannot await it since it is not an asynchronous method.
For your case, you should start it before showing the Widget that would contain the InAppWebView instance where you want to transfer it.

Currently, because of this, your headless WebView is not ready when you are calling the InAppWebView instance, so you will have 2 different WebView.

**Comment by hossameldinmi** [comment]
@pichillilorenzo It's almost the same as #2199, but it occurs on flutter web.
