### ISSUE TITLE
Is there anyway to open a new tab in flutter?

### ISSUE THREAD

**Issue by Karatla** [pichillilorenzo/flutter_inappwebview#211]
First thanks author provide this good plugin for us. Please keep updating! I like your plugins.

For now I have a problem I want to build a browser app but I do not know how to make multiple tabs in flutter . Every tab or web page I base on your plugin by appWebView . I try to use pageView to control all tabs but works not well and I do not know if it is a suitable way. Is there anyone can give me a solution? Thanks!

I hope author could update a function to make multiple tabs . Thanks so much if could do it!

**Comment by pichillilorenzo** [comment]
Hi @Karatla! Thanks!

However, for something like multiple tabs, you need to implement it your self using the various flutter widgets and gestures and instantiating a WebView for each "tab" of your browser app.

That's because the goal of this plugin for `InAppWebView` is to provide the most complete cross-platform WebView with which to create everything you want.

So, I think that "multiple tabs" is outside of the scope because it is something you can implement your self, just as I said before.

However, I was already thinking about making a tutorial on how to make a browser app using `InAppWebView` (maybe something like the **Chrome** browser). Also, I have in mind another tutorial to show better some use cases. But these things take time. I will make them as soon as possible!

**Comment by Karatla** [comment]
Thank you so much !
