### ISSUE TITLE
How to load script javascript on webview does not work.

### ISSUE THREAD

**Issue by pathapong** [pichillilorenzo/flutter_inappwebview#219]
I encountered a problem with the application that the inappwebview webview does not load scripts such as Javascript and others do not work.
I want to know that How should it be fixed? How to get the script to load.
The example below
![78762799_570242057162569_184701937533321216_n](https://user-images.githubusercontent.com/6447731/70708600-7d2b6e00-1d0d-11ea-9c13-7cb29f12ac0b.jpg)

Thank you

**Comment by pichillilorenzo** [comment]
Please, next time use the issue template when you create an issue here. I created it to be used as it gives me useful information in order to debug the plugin.

However, can you post the code you are using? Maybe there are some options that breaks your javascript code.
Also, in your `initialOptions` try to add:
```dart
...

initialOptions: InAppWebViewWidgetOptions(
    inAppWebViewOptions: InAppWebViewOptions(
      debuggingEnabled: true,
    ),
    androidInAppWebViewOptions: AndroidInAppWebViewOptions(
      domStorageEnabled: true
    )
),

...
```

- `domStorageEnabled` is used to enable DOM storage API on Android
- `debuggingEnabled` to enable debugging on Android using the Chrome Browser to inspect the WebView and see if there are some javascript errors (URL to use on Chrome: `chrome://inspect/#devices`). On iOS, it is always enabled and you need to use Safari.

**Comment by pathapong** [comment]
> ```dart
> androidInAppWebViewOptions: AndroidInAppWebViewOptions(
>       domStorageEnabled: true
>     )
> ```

Thank you for the answer. @pichillilorenzo
