### ISSUE TITLE
How to get callback results 

### ISSUE THREAD

**Issue by Karatla** [pichillilorenzo/flutter_inappwebview#227]
I do not want to load a url immediately when I click a url in web by inappwebview . I want to get control or result first and depend on me if the web could load new url . I used useShouldOverrideUrlLoading to achieve this and it works well in some url but some url not working .

**Comment by Karatla** [comment]
Or when could you update new function like get 
Click event in webview

**Comment by Karatla** [comment]
Like this webview. performLongClick() in android webview

**Comment by pichillilorenzo** [comment]
@Karatla it depends on the link type. For example, if the link has `target=_blank`, then you need to use the 'onTargetBlank` event (with `useOnTargetBlank` option to `true`) to capture clicks on that link. 
Otherwise, can you post the link to that webpage which `shouldOverrideUrlLoading` is not called? Tell me which is the link (or the links) of that webpage that is not captured when the user clicks on it, thanks!

However keep in mind that `onTargetBlank` will be removed in the next release with another event called `onCreateWindow`! Also, `shouldOverrideUrlLoading` will be updated.

**Comment by Karatla** [comment]
@pichillilorenzo
Thank you . It was my mistake. When I use targetblank it worked fine.By the way could you provide a function which can listen onlongpresse for url in web?
Thank you so much.

**Comment by pichillilorenzo** [comment]
Ok, I will check about that!
