### ISSUE TITLE
[Android] `InAppWebViewController.callAsyncJavaScript` is not working on latest Android WebView.

### ISSUE THREAD

**Issue by laishere** [pichillilorenzo/flutter_inappwebview#2477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`InAppWebViewController.callAsyncJavaScript` future will never complete on com.google.android.webview.canary v133.0.6917.0.
The web page loads normally.

It works on the old version of the same emulator v83.0.4103.106 (comes with the system).

### Expected Behavior

`InAppWebViewController.callAsyncJavaScript` should work correctly.

### Steps with code example to reproduce

<details>
<summary>Steps with code example to reproduce</summary>

```dart
await controller.callAsyncJavaScript(functionBody: 'return 1;');
```
</details>

### Stacktrace/Logs

<details>
<summary>Stacktrace/Logs</summary>

```
No logs. It hangs forever.
```
</details>

### Flutter version

v3.24.3

### Operating System, Device-specific and/or Tool

Android 30

### Plugin version

v6.1.5

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by laishere** [comment]
It's because of the `window.flutter_inappwebview.callHandler` is not ready after `loadUrl`. After waiting for a while, it's working.
Is it normal?

**Comment by laishere** [comment]
I think it should wait until `callHandler` is available before calling it inside `callAsyncJavaScript`, otherwise, we will never get it completed. Or at least, an error should be raised in `callAsyncJavaScript`.

**Comment by laishere** [comment]
I tried adding a completer that is triggered after `onLoadStop`. It works, but it's overkill.
I then switched to using `onLoadStart`, and now both `callHandler` and `callAsyncJavaScript` are working.

**Comment by pichillilorenzo** [comment]
Check the documentation: https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/PlatformInAppWebViewController/callAsyncJavaScript.html

In general, you can’t evaluate JavaScript code in the webpage if the webpage itself of the WebView isn’t ready “enough”.
“onLoadStop” is a good point to evaluate JavaScript code.
Otherwise, if you need something to be executed on load startup, then you should use User Scripts At Document Start: https://inappwebview.dev/docs/webview/javascript/user-scripts
