### ISSUE TITLE
Text Copy paste Selections not working on Android devices

### ISSUE THREAD

**Issue by virskor** [pichillilorenzo/flutter_inappwebview#286]
## Environment

Flutter 1.12.13+hotfix.7
Dart 2.7.0

all Android devices got same issue

## Description
This bug is not appeared on IOS, but all android devices could not paste or copy text into webview input tags.

Selection toolbar is working, but try to copy and paste will show you the problem.
Thanks!

**Comment by ohjs88** [comment]
same problem.

**Comment by atrn0** [comment]
This might be helpful: https://github.com/pichillilorenzo/flutter_inappwebview/issues/235#issuecomment-569251361

I think this problem is related to Platform View. Platform View is still in a developer preview and has some limitations (https://github.com/flutter/flutter/wiki/Android-Platform-Views#limitations-2).
You can use [InAppBrowser](https://github.com/pichillilorenzo/flutter_inappwebview#inappbrowser-class) or [ChromeSafariBrowser](https://github.com/pichillilorenzo/flutter_inappwebview#chromesafaribrowser-class) for now.

Similar issue:  https://github.com/flutter/flutter/issues/24585

**Comment by mdemarco15** [comment]
is there any news on #286?
