### ISSUE TITLE
Click on the HTML input box can't open the system input keyboard

### ISSUE THREAD

**Issue by dchaofei** [pichillilorenzo/flutter_inappwebview#31]
When loading an HTML page using the embedded WebView in Android, if there is an input box in the html page.When the input box gets the focus, the system input method keyboard does not pop up correctly.
How can the webview open system keyboard input method？
Thank!

**Comment by dchaofei** [comment]
Flutter_webview_plugin can open the system input keyboard, But I think flutter_inappbrowser has more features

**Comment by pichillilorenzo** [comment]
For the Inline webview widget, It not depends on me but on the implementation of [AndroidView](https://docs.flutter.io/flutter/widgets/AndroidView-class.html) from the Flutter Team! They need to update their implementation in order to do something like this! 😞 

The Flutter_webview_plugin can do this because the widget is not integreted in the Flutter widget tree.

**Comment by ShiroYacha** [comment]
Hi, 
I see that this is still pending from the Flutter dev side but I want to know if there is a workaround for my scenario. Basically I only need keyboard because I want to log the user in on the sites. I wonder if I could do so by using another full screen web page and persists the cookies to the web view? I am quite a noob on browsers, is this achievable using inappbrowser?

Best!

**Comment by pichillilorenzo** [comment]
This has been fixed. Also, this plugin changed its name to `flutter_inappwebview`. The current latest version now is `2.1.0+1`. So, you can change your dependency in`flutter_inappwebview: ^2.1.0+1`.
