### ISSUE TITLE
MissingPluginException when calling InAppWebViewController

### ISSUE THREAD

**Issue by AlexVincent525** [pichillilorenzo/flutter_inappwebview#336]
## Environment

**Flutter version:** 1.17.0 (stable)
**Plugin version:**  3.1.0
**Android version:** Android 10
**Device information:** Emulator/OnePlus IN2020

## Description

Calling any methods in `InAppWebViewController` throws an unimplement error.

## Steps to reproduce

1. Implement a webView widget in some pages.
2. Define method `onWebViewCreated` and inside this call `_webViewController = controller`.
3. Call `_webViewController.evaluateJavascript(...)` or any methods and it throws error.

## Images
![image](https://user-images.githubusercontent.com/15884415/81532724-6f027c00-9397-11ea-9474-7d8562664010.png)

![image](https://user-images.githubusercontent.com/15884415/81532641-4d08f980-9397-11ea-9121-938a428651d0.png)

## Stacktrace/Logcat
```
E/flutter (16827): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_1)
E/flutter (16827): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (16827): <asynchronous suspension>
E/flutter (16827): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (16827): #2      InAppWebViewController.evaluateJavascript (package:flutter_inappwebview/src/in_app_webview_controller.dart:926:31)
E/flutter (16827): #3      _InAppBrowserPageState.dispose (package:openjmu/widgets/webview/in_app_webview.dart:91:24)
......
```

**Comment by AlexVincent525** [comment]
@pichillilorenzo I think it might be related to id with the channel?

**Comment by pichillilorenzo** [comment]
This behavior is correct. That happens in your case because you are calling the webview controller method inside the `dispose()` widget method.
Any webview controller method, such as `evaluateJavascript` is an async method, so execute asynchronously. It means that when you call a webview controller method at dispose widget time, your webview has already been disposed (it has been removed from the widget tree), so you can't communicate with it, because there isn't any webview anymore.
If you need to set `window.onbeforeunload=null` with javascript, you need to do it before the `dispose` widget method is called! For example, you can place it in the `onLoadStop` method.

**Comment by AlexVincent525** [comment]
Okay, but the reason I'm override `onBeforeUnload` is from another issue, I'll open it later.

BTW, glad to see you coming back after these months. 😄
