### ISSUE TITLE
v3.0.0 does not get cookies on IOS

### ISSUE THREAD

**Issue by weiwei00200** [pichillilorenzo/flutter_inappwebview#345]
I use v3.0.0 flutter_inappwebview library could not get cookies on IOS. But it works on Android phones.

**Comment by pichillilorenzo** [comment]
See https://github.com/pichillilorenzo/flutter_inappwebview/issues/338.
There is an example setting a custom cookie on https://flutter.dev/ as an example (https://github.com/pichillilorenzo/flutter_inappwebview/issues/338#issuecomment-626690560).
Also, consider that `CookieManager` is available from iOS 11.0+.

The example I referenced does it work?
Otherwise, could you post here a simple code example that is not working for you?
