### ISSUE TITLE
CookieManager iOS started to fail

### ISSUE THREAD

**Issue by huangweigan** [pichillilorenzo/flutter_inappwebview#350]
CookieManager iOS started to fail

**Comment by pichillilorenzo** [comment]
What do you mean? Could you provide a more detailed description?

See https://github.com/pichillilorenzo/flutter_inappwebview/issues/338.
There is an example setting a custom cookie on https://flutter.dev/ as an example (https://github.com/pichillilorenzo/flutter_inappwebview/issues/338#issuecomment-626690560).
Also, consider that `CookieManager` is available from iOS 11.0+.

The example I referenced does it work?
Otherwise, could you post here a simple code example that is not working for you?
