### ISSUE TITLE
postUrl example

### ISSUE THREAD

**Issue by mikylucky** [pichillilorenzo/flutter_inappwebview#352]
Hi, can you provide an example on how to populate the `postData` object in a `postUrl` call?

A fake `postData` object would be nice to see

**Comment by pichillilorenzo** [comment]
You need to import the `import 'dart:convert';` library and encode your POST body string into a `Uint8List` data.

To do that you can use, for example, the `utf8.encode()` method.

Here is an example:
```dart
onWebViewCreated: (InAppWebViewController controller) {
  var data = "firstname=Foo&lastname=Bar";
  controller.postUrl(url: "http://192.168.1.123:8082/test-ajax-post", postData: utf8.encode(data));
},
```

**Comment by masiJR** [comment]
onWebViewCreated: (InAppWebViewController controller) {
  var data = "firstname=Foo&lastname=Bar&hash=8ZaZJ3Cc5n89LoLBBTwnpJ3YuQSulYnekJtCSO7bfE+9hMGtHaj";
  controller.postUrl(url: "http://www.example.com", postData: utf8.encode(data));
},


I got nothing in webview. I know that because of my hash key is have plus (+) symbol that make webview can't load.
Question: How can i postData with hash?

**Comment by RemmoYu** [comment]
@masiJR  Uri.encodeComponent(yourString)

**Comment by masiJR** [comment]
@RemmoYu  Thank you bro.

**Comment by paraslamsong** [comment]
@pichillilorenzo 
How can we post formdata in initial request?

**Comment by Sumit258000** [comment]
@RemmoYu Can you please explain your answer I am facing same problem when I am sending Form Data `+` symbol is replaced by space how can I avoid that?
