### ISSUE TITLE
'flutter_inappwebview/flutter_inappwebview-Swift.h' file not found

### ISSUE THREAD

**Issue by angebagui** [pichillilorenzo/flutter_inappwebview#360]
'flutter_inappwebview/flutter_inappwebview-Swift.h' file not found on 3.2.0

**Comment by pichillilorenzo** [comment]
- Try to clean your project using `flutter clean`
- Try to run `pod install` inside `ios` folder
- Try to build using Android Studio
- Try to build using Xcode (open it from Android Studio)

Let me know if some of these or a combination of these make it work.

**Comment by angebagui** [comment]
I have tried it but I have always  'flutter_inappwebview/flutter_inappwebview-Swift.h' file not found on 3.2.0

**Comment by pichillilorenzo** [comment]
If you create a new fresh Flutter app with adding support to Swift (it should be added by default for new Flutter projects, otherwise you can use `flutter create --androidx -i swift`), do you have any problems using the example in the `README.md`??
If this works, then it means you need to add support for Swift in your Flutter app!

Have you read the [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios) Section??
