### ISSUE TITLE
need onUrlChanged method for ChromeSafariBrowser 

### ISSUE THREAD

**Issue by samin-fs** [pichillilorenzo/flutter_inappwebview#401]
I want to know when redirect URL changed in ChromeSafariBrowser.
in InAppBrowser I can see the Url change through the "onLoadStart" method. but using custom tabs, I cant.

**Comment by pichillilorenzo** [comment]
It's not possible to have an `onUrlChanged` event for ChromeSafariBrowser because Chrome Custom Tab (Android) and SFSafariViewController (iOS) doesn't have such feature.
The only thing that is possible is **Authentication Flow using Deep Linking** that I need to implement.

Instead, if you need more control over your flow, you should use `InAppWebView` widget or `InAppBrowser` class.
