### ISSUE TITLE
shouldOverrideUrlLoading can't listen to all URL

### ISSUE THREAD

**Issue by sxs1995** [pichillilorenzo/flutter_inappwebview#411]
![image](https://user-images.githubusercontent.com/22333956/85262141-f0bded00-b49f-11ea-9fd5-0f3c28d3bfa4.png)

It can't listen to all URL , when the website is navigated by javascript, onLoadStart shouldOverrideUrlLoading and onLoadStop isn't called.  the route is not listened.

**Comment by pichillilorenzo** [comment]
Because you need to use `onUpdateVisitedHistory` event: Event fired when the host application updates its visited links database. This event is also fired when the navigation state of the InAppWebView changes, for example through the usage of the javascript [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) functions.

When you are in a Single-page application and use javascript, for example with a framework such as angular or react, to navigate your routes using the router module (in this case you are not loading an URL into the WebView), then you should use `onUpdateVisitedHistory` event.

**Comment by sxs1995** [comment]
I try to use `onUpdateVisitedHistory`, but I get the same URL.

**Comment by pichillilorenzo** [comment]
Did you resolve it?
If not, could you post an example that is not working for you? Thanks

**Comment by sxs1995** [comment]
yes, I resolve it. I get this URL by `controller.getUrl(); `

**Comment by sxs1995** [comment]
> @sxs1995 Hi, I am facing the same issue, js called "document.location = 'js://webview?xxx=xxxx'", onLoadStart shouldOverrideUrlLoading and onLoadStop isn't called, could you tell me how you solved it?

It's been so long I can't remember it clearly, maybe I'm using `Controller.getURL ()` in the `OnUpdateVisiedHistory` to determine the current URL .I'm sorry I can't give you an exact answer.

**Comment by brandoneedyou** [comment]
@sxs1995 Thanks
