### ISSUE TITLE
open platform url

### ISSUE THREAD

**Issue by alexmik95** [pichillilorenzo/flutter_inappwebview#417]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 1.20.0-1.0.pre.156 |
| Plugin version       | 3.4.0+1 |
| Android version      | 9.0.0 |
| iOS version          | X |
| Xcode version        | X |

Device information: 

## Description
it seems that the plugin doesn't support launching platform url as `tel:`, `whatsapp:` or `mailto:`.

**Expected behavior:** 
Try to handle the url with a platform call and open relative app

**Current behavior:** 
Error loading page `net::ERR_UNKNOWN_URL_SCHEME`, error code `-10`

## Steps to reproduce
Simply try to open these type of url

## Workaround
use `url_launcher` plugin and handle error in `on_load_error` declaration:
```dart
onLoadError: (InAppWebViewController controller, String url, int i, String s) async {
  print('CUSTOM_HANDLER: $i, $s');
  _webViewController.goBack();
  String action = url.split(':').first;
  List<String> customActions = ['tel', 'whatsapp', 'mailto'];
  bool isCustomAction = customActions.contains(action);
  if (isCustomAction) {
    if (await canLaunch(url)) {
      await launch(
        url,
      );
    } else {
      throw 'Could not launch $url';
    }
  }
}
```

**Comment by pichillilorenzo** [comment]
A WebView is just a WebView, not a Browser such as Google Chrome or Safari.

For example, if you create an Android App using Java and you use the Android [`WebView`](https://developer.android.com/reference/android/webkit/WebView) class, you will notice that it has the same behavior, that is it doesn't know what is `whatsapp:` or `fb:` protocol/scheme.

What you posted here is not a workaround but a solution for what you want to do, except that you should use the `shouldOverrideUrlLoading` event instead of `onLoadError`.
To use the `shouldOverrideUrlLoading` event, you need to enable it with `useShouldOverrideUrlLoading: true` option. 

Here is an example:
```dart
initialOptions: InAppWebViewGroupOptions(
  crossPlatform: InAppWebViewOptions(
    debuggingEnabled: true,
    useShouldOverrideUrlLoading: true
  ),
),
shouldOverrideUrlLoading: (controller, shouldOverrideUrlLoadingRequest) async {
  String action = shouldOverrideUrlLoadingRequest.url.split(':').first;
  List<String> customActions = ['tel', 'whatsapp', 'mailto'];
  bool isCustomAction = customActions.contains(action);
  
  if (isCustomAction) {
    if (await canLaunch(url)) {
      // Launch the App
      await launch(
        url,
      );
      // and cancel the request
      return ShouldOverrideUrlLoadingAction.CANCEL;
    }
  }
  
  return ShouldOverrideUrlLoadingAction.ALLOW;
},
```

**Comment by ycv005** [comment]
Helpful. I think you need to mention in documentation.
