### ISSUE TITLE
[Question] When `takeScreenshot` returns null?

### ISSUE THREAD

**Issue by ggirotto** [pichillilorenzo/flutter_inappwebview#535]
The `takeScrenshoot` function mentions that it may return null if it wasn't able to capture the screenshot. Assuming that I am trying to take the screenshot in `onLoadStop` callback when the function returns null? In my specific scenario, it seems pretty random the moments that it returns null. If I keep rebuilding the app, sometimes it happens, sometimes it doesn't happen.

**Comment by pichillilorenzo** [comment]
It could return `null` when the WebView is not ready enough to be able to take it.
It could happen when you are trying to taking a screenshot of a WebView that is not rendered yet.
This is something related to the OS itself. So, unfortunately, I can’t tell you when you are able to take screenshots of the WebView. For sure you need to wait at least the `onLoadStop` event. If it returns `null`, you can try for example to wait 1 second after the `onLoadStop` event is fired and try to retake it.
However I think that this issue is something more related to Android then iOS.
