### ISSUE TITLE
how do i inject js before page's js executed

### ISSUE THREAD

**Issue by godfeather** [pichillilorenzo/flutter_inappwebview#570]
I have a case : before the page's js executed to define a function or variables for page's js; when the page's js ready, it will call the variable or function;

**Comment by godffather** [comment]
but in this time, when my page's load's ready,the page's js throw a error; so i need a function , it has a param of String, it mean's a js section, i will execute the js at the time page start load(for example WebView's onLoad callback);the function will inject the js section before all page's js executed

**Comment by pichillilorenzo** [comment]
To inject JavaScript before the page is “executed” you need to use the new feature `UserScript` with injection time `AT_DOCUMENT_START`.
However, on Android, because there is no official API as on iOS, the scripts are not guaranteed to be executed before the page is “executed”.
See the “User Scripts” section in this new [article](https://medium.com/flutter-community/whats-new-in-inappwebview-5-null-safety-new-features-bug-fixes-11c9e2cadab2) to understand how it works.
