### ISSUE TITLE
onReceivedHttpAuthRequest is not called in IOS

### ISSUE THREAD

**Issue by miladasfa** [pichillilorenzo/flutter_inappwebview#583]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)

## Description
I have created an app to load the website using NTLM for authentication. i am using onReceivedHttpAuthRequest to proceed with the authentication. it is work perfectly in Android, but onReceivedHttpAuthRequest is not called in IOS.

onReceivedHttpAuthRequest: (InAppWebViewController controller, HttpAuthChallenge challenge) async {
           return re=HttpAuthResponse(username: _userName, password: _password, action: 
                            HttpAuthResponseAction.PROCEED, permanentPersistence: true);
}

I will really appreciate if anyone can help m e on this issue.

Thank you.

**Comment by albatrosify** [comment]
Oh interesting, I was just thinking about opening a bug for this. I am deeply in trouble right now, as I am using headlessInAppWebView for navigating through pages to grab data for my app. However in some occasions I need NTLM. 
I thought this was not possible at all with inappwebview, but interesting that you say it works on android. 

I hope this can be fixed in near future, as this is completely rendering InAppWebView useless for me right now. :(

**Comment by ricardonogpereira** [comment]
Hello, I also had the same problem in **NTLM** authentication in IOS and the method was not started due to the absence of calls: **NSURLAuthenticationMethodNegotiate** and **NSURLAuthenticationMethodNTLM**.
I located the swift file that makes this call that is on the path: flutter_inappwebview / ios / Classes / InAppWebView.swift
When adding locally for testing, it worked!
...
 public func webView(_ webView: WKWebView, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {

        if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodHTTPBasic ||
            challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodDefault ||
            challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodNegotiate ||
            challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodNTLM ||
            challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodHTTPDigest {
....
Getting something like above.
I have already notified the developer to evaluate include this and have this verification.
Thanks
Ricardo Nogueira
