### ISSUE TITLE
"reload" not work when no internet.

### ISSUE THREAD

**Issue by dodatw** [pichillilorenzo/flutter_inappwebview#587]
I want to handle "no internet" case.
I plan to pop up a dialog when "onLoadError".
There have a "retry" button on dialog for user reload after network available.

But I found "InAppWebViewController.reload" no function when load page fail before. (It work when load page success before).

Now, I have a workaround that call "InAppWebViewController.loadUrl" .
It's work, but not good solution. (loadUrl only can load the first url that I have).

P.S. I am working on iOS

doda

**Comment by PawelSzymanski89** [comment]
same problem here

**Comment by pichillilorenzo** [comment]
This is how it works on iOS (check https://stackoverflow.com/questions/45706866/wkwebview-reload-cant-refresh-current-page/45708014).
You should get the current URL with `getUrl` method and check the current URL is `null` or not.
If it is `null`, you need to use `loadUrl` because there is no URL to be reloaded, otherwise you can call `reload` method.
