### ISSUE TITLE
onPrint event should be fired for iframes too

### ISSUE THREAD

**Issue by mxmihai** [pichillilorenzo/flutter_inappwebview#588]
Is it possible the "onPrint" to be activated on whatever ".print()" method from JS, and not only on "window.print()"? In case it's needed to print an iframe (example: "iframe_variabile.contentWindow.print()"), the event is not triggered. Thank you.

**Comment by pichillilorenzo** [comment]
Unfortunately it is not possible. You need to consider that the `onPrint` event is implemented using `JavaScript` because there is no official API about it, and, on Android, is not possible to inject JavaScript code that is available for all iframes like on iOS.
However, you can print the current page using the `printCurrentPage` method, so you can implement your own logic.
