### ISSUE TITLE
Camera photo upload issue

### ISSUE THREAD

**Issue by tommasobellini** [pichillilorenzo/flutter_inappwebview#640]
Hi All,
on my react.js webapp i have a lot of forms for uploading images. 
When i click on "camera" icon it asks me if i want use camera, videocamera or choose from file manager and that's good.
My issue is that when i try to take photo from camera my webapp cannot load it because it recognized as a 'video' file type instead of 'image'. How is it possible? Have i to handle it in flutter side? I tried to change packages on react.js webapp but same issue. In iOS is working good because using 'ChromeSafariBrowser', this is related only for android platform.
Anyone have any  idea?

thanks
Tommaso

I attach an example and logs:

![WhatsApp Image 2021-01-11 at 17 52 47](https://user-images.githubusercontent.com/48091989/104212827-ebbd8c80-5435-11eb-8446-7907e820cb75.jpeg)

![WhatsApp Image 2021-01-11 at 17 52 47 (1)](https://user-images.githubusercontent.com/48091989/104212821-ea8c5f80-5435-11eb-9a2d-f0ea82d8b1d3.jpeg)

![Schermata 2021-01-11 alle 17 45 44](https://user-images.githubusercontent.com/48091989/104212649-ba44c100-5435-11eb-9daa-d162da32ed50.png)

**Comment by Josimarcsilva** [comment]
I have the same problem.
I made some textes I verified that the problem is the field is defined for images or videos.

That way it doesn't work:
<input type = "file" accept = "image / *, video / *">

But this way it works:
<input type = "file" accept = "image / *">

That is, using "<input type =" file "accept =" image / *, video / * ">" if the field is set to image or video, when trying to take a photo it loads as a video.

**Comment by pichillilorenzo** [comment]
What version of the plugin are you using?
Have you tried the new version 5.0.0?

**Comment by Josimarcsilva** [comment]
I'm using

dependencies:
  flutter_inappwebview: ^4.0.0+4

**Comment by Josimarcsilva** [comment]
Version 5.0 worked for me. Thanks!

dependencies:
  mime: ^1.0.0
  uuid: ^3.0.0-nullsafety.1
  device_info: ^2.0.0-nullsafety.2
  flutter_inappwebview: ^5.0.4-nullsafety.1
