### ISSUE TITLE
iOS implementation of ShouldInterceptRequest

### ISSUE THREAD

**Issue by iBog** [pichillilorenzo/flutter_inappwebview#675]
• Flutter version 1.26.0-17.3.pre at G:\BackUp\flutter
    • Framework revision 4b50ca7f7f (5 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

## Task

Implement caching mechanism for WebView, and replace images from web page, 
with already cached and saved to local,

## Description

Need some analog to existing mechanism androidShouldInterceptRequest for iOS, 
according to "https://pub.dev/packages/iwebview_flutter" it's technically possible.
Possibly something similar already exists in flutter_inappwebview?

**Comment by pichillilorenzo** [comment]
Unfortunately no, `iwebview_flutter` is using iOS Private API such as `wk_registerScheme`.
I have already tried it, but Apple won't accept your App because of this (for example see this post [Question on using private API in WKWebView](https://developer.apple.com/forums/thread/87474)).
The only official iOS API that allows something similar is [WKURLSchemeHandler](https://developer.apple.com/documentation/webkit/wkurlschemehandler), which, in my plugin, has been mapped as the `onLoadResourceCustomScheme` event.
To intercept requests that have custom schemes (so, `http` and `https` can't be registered unfortunately!), you need to register the custom schemes you want to listen using the `InAppWebViewOptions.resourceCustomSchemes` option.

**Comment by iBog** [comment]
Thanks for clarification!
