### ISSUE TITLE
Hybrid Composition

### ISSUE THREAD

**Issue by cmd-dev** [pichillilorenzo/flutter_inappwebview#681]
When will Hybrid Composition be implemented? Any approximate date? As the flutter_inappwebview plugin is much slower without the implementation, compared to webview_flutter which supports it and hence can provide better performance.

**Comment by pichillilorenzo** [comment]
The master branch contains already Hybrid Composition from half a year using `useHybridComposition` android-specific option.
Unfortunately, I was too busy with my job to work on this plugin these months.
I'm working on it again since January and I'm adding the last fixes and features I was already working on.
The new version 5.0.0 however will have a lot of breaking changes.
