### ISSUE TITLE
Access http headers of responses

### ISSUE THREAD

**Issue by danielkono** [pichillilorenzo/flutter_inappwebview#693]
## Environment

**Flutter version:** 
1.22.6
**Plugin version:**    
4.0.0+4
**Android version:**    
10
**iOS version:**
13.2

## Description

I want to track http responses within the web view and read out the corresponding http headers.
The UseCase is to perform a login in the webview which response with a http header containing the auth token.

**What you'd like to happen:** 

Adding a possibility to track http responses and read out http headers

**Comment by pichillilorenzo** [comment]
Unfortunately, it is impossible to track HTTP responses with HTTP headers (that's not because I didn't implement it, but because there isn't any method on the native side to do that! See WebView for Android and WKWebView for iOS).

However, you can intercept requests using the `shouldOverrideUrlLoading` event (you need to enable it with `useShouldOverrideUrlLoading: true` webview option), cancel the navigation, and, then, you can make an HTTP request (using the `http` dart library) to the server you want to read the auth token.

**Comment by pichillilorenzo** [comment]
Sorry, it should be possible at least on iOS using the new `iosOnNavigationResponse` event (plugin version 5.0.0+), but I need to add headers to the response received on the dart side.

**Comment by danielkono** [comment]
Thanks for the fast response.
Then i will try `shouldOverrideUrlLoading` as you suggested.
