### ISSUE TITLE
Content-Type header is lost if fetch request is intercepted

### ISSUE THREAD

**Issue by gasaichandesu** [pichillilorenzo/flutter_inappwebview#711]
- [x] I have read the [README](https://github.com/pichillilorenzo/flutter_inappwebview/blob/master/README.md)
- [x] I have already searched for the same problem
- [x] I have read and done the setup for Android: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for Android](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)
- [x] I have read and done the setup for iOS: [IMPORTANT Note for Android and iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android-and-ios) and [IMPORTANT Note for iOS](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)
- [x] I have ran the sample app and it does not work there

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      | 2.0.1 |
| Plugin version       | 4.0.0+4 |
| Android version      | 10 |
| iOS version          | 14 |
| Xcode version        | 12 |

Device information: Honor 10, iPhone X (not sure which modification exactly)

## Description

On my website I have multiple forms which are submitted with Fetch API using FormData as a request body. Content-Type header is not  explicitly set, but it is set implicitly by a browser. Everything works fine in a browser itself and in an InAppWebView. However, I also need to pass additional authorization header with a request, so I am using shouldInterceptFetchRequest callback. Authorization header is sent with no problems, but there is no Content-Type header with a request, which leads to my backend treating request body as an empty body and validation errors happen.

Also, tried updating to 5.0+ version. It resulted in shouldInterceptFetchRequest not being called at all, so downgraded back to 4.0.0 since it is somehow working.

**Expected behavior:** Content-Type header should be sent along with additional header

**Current behavior:** Content-Type header is lost completely

## Steps to reproduce

Initialize an InAppWebView with shouldInterceptFetchRequest callback
```dart
shouldInterceptFetchRequest: (controller, FetchRequest fetchRequest) async {
    final fetchRequestWithAuthorization = fetchRequest
        ..headers['Authorization'] = 'Bearer $token';
    return fetchRequestWithAuthorization;
},
```

**Comment by pichillilorenzo** [comment]
Tested on the latest version and it's working as expected on both iOS (real iPhone) and Android (Emulator API 30).

This is my Flutter test code:
```dart
import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (Platform.isAndroid) {
    await AndroidInAppWebViewController.setWebContentsDebuggingEnabled(true);
  }

  runApp(new MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {

  static const SERVER_URL = "http://192.168.1.129:8082";

  InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
    crossPlatform: InAppWebViewOptions(
      useShouldInterceptFetchRequest: true
    ),
    android: AndroidInAppWebViewOptions(
      useHybridComposition: true,
    ),);

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          appBar: AppBar(title: Text("Intercept Fetch Request Example")),
          body: SafeArea(
              child: Column(children: <Widget>[
                Expanded(
                  child: InAppWebView(
                    initialData: InAppWebViewInitialData(data: """
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>InAppWebViewFetchTest</title>
    </head>
    <body>
        <h1>InAppWebView Fetch Test</h1>
        <script>
          window.addEventListener('flutterInAppWebViewPlatformReady', function(event) {
          
            fetch(new Request("${SERVER_URL}/test-fetch")).then(function(response) {
                console.log("fetch success");
            }).catch(function(error) {
                console.log("fetch error");
            });
            
          });
        </script>
    </body>
</html>
                    """),
                    initialOptions: options,
                    shouldInterceptFetchRequest: (controller, fetchRequest) async {
                      print("shouldInterceptFetchRequest CALLED!");

                      if (fetchRequest.headers == null) {
                        fetchRequest.headers = {};
                      }
                      fetchRequest.headers!['Authorization'] = 'Bearer HERE_MY_TOKEN';
                      return fetchRequest;
                    },
                    onConsoleMessage: (controller, consoleMessage) {
                      print(consoleMessage);
                    },
                  ),
                ),
              ]))),
    );
  }
}
```

I also set up a local Node.js Express server that simply prints out on the console the headers received:
```javascript
const express = require('express');
const cors = require('cors');
const app = express();

// Parse URL-encoded bodies (as sent by HTML forms)
app.use(express.urlencoded());

app.use(cors());

// Parse JSON bodies (as sent by API clients)
app.use(express.json());

app.get("/test-fetch", (req, res) => {
  console.log(JSON.stringify(req.headers));
  res.send('');
  res.end();
});

app.listen(8082);
```

When the `fetch` javascript function is called, the Node.js server receive correctly the GET request and prints out the headers with `Authorization` header and value.

These are the headers from the iPhone:
```json
{
	"host": "192.168.1.129:8082",
	"origin": "null",
	"connection": "keep-alive",
	"if-none-match": "W/\"4-qUqP5cyxm6YcTAhz05Hph5gvu9M\"",
	"accept": "*/*",
	"user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
	"authorization": "Bearer HERE_MY_TOKEN",
	"accept-language": "it-it",
	"accept-encoding": "gzip, deflate"
}
```

These are the headers from the Android Emulator:
```json
{
	"host": "192.168.1.129:8082",
	"connection": "keep-alive",
	"authorization": "Bearer HERE_MY_TOKEN",
	"user-agent": "Mozilla/5.0 (Linux; Android 11; sdk_gphone_x86_arm Build/RSR1.201013.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36",
	"accept": "*/*",
	"origin": "null",
	"x-requested-with": "com.gp.flutterapp",
	"accept-encoding": "gzip, deflate",
	"accept-language": "en-US,en;q=0.9",
	"if-none-match": "W/\"0-2jmj7l5rSw0yVb/vlWAYkK/YBwk\""
}
```

As you can see, the server receives correctly the headers with also the `Authorization` header.

Because of my example, I needed to enable HTTP (non-HTTPS) support for both Android (see [here](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-android)) and iOS (see [here](https://github.com/pichillilorenzo/flutter_inappwebview#important-note-for-ios)).

Also, because this event (and also the Ajax ones) is implemented using JavaScript (there is no official API to do it on Android and iOS native WebViews), this plugin, when `useShouldInterceptFetchRequest` is enabled, wraps the native `fetch` javascript function to be able to intercept it.
On Android, because there is no way to execute javascript before the web page loads, it tries to inject the wrapper as soon as possible.
So, if your `fetch` calls are called too quickly, on Android, they cannot be intercepted.
This is not valid for iOS because native WebViews allow injecting custom javascript before the page loads any other resources.
So, In my example, as you can see, before calling `fetch`, I listen to the `flutterInAppWebViewPlatformReady` event that is dispatch as soon as possible. This way I know for sure that on Android the `fetch` wrapper is loaded and then you can intercept fetch requests.
You can also create a global flag variable to be set when the `flutterInAppWebViewPlatformReady` event is dispatched so that you can check if that global flag variable is `true` or not before calling `fetch`.
Obviously, that depends on the fact you can change or not the current code of the webpage.
If you cannot change it, then, unfortunately on Android, you cannot intercept requests called too quickly before the `flutterInAppWebViewPlatformReady` event is dispatched.

**Comment by gasaichandesu** [comment]
Thanks for the explanation, it helped me to move further in understanding the problem. Indeed, as soon as I started listening to `flutterInAppWebViewPlatformReady` event, intercepting went ok. However, the issue with content-type header persisted. After further investigating and inspecting plugin's source code, I found out that request body is converted to array of bytes. Then I tried to make similar fetch request writing my own JS script. And it became clear that as soon as request body is converted this way, browser does not understand that it is a form data anymore. So I found a workaround with manually setting a content-type header. It looks like this:
```dart
 shouldInterceptFetchRequest:
                              (controller, FetchRequest fetchRequest) async {
                            final fetchRequestWithAuthorization = fetchRequest
                              ..headers['Authorization'] =
                                  'Bearer ${tokenSnapshot.data}';

                            if (fetchRequest.method == 'post') {
                              final boundary = String.fromCharCodes(
                                  fetchRequest.body.sublist(2, 40));

                              fetchRequestWithAuthorization
                                      .headers['Content-Type'] =
                                  'multipart/form-data; boundary=$boundary';
                            }

                            return fetchRequestWithAuthorization;
                          },
```
With this code my backend correctly parses the request and finally I can move on to develop new features in my app. Hope it helps for other people facing this issue.

**Comment by pichillilorenzo** [comment]
Ok, now I understand what you mean! The problem is that, obviously, I cannot send javascript native objects (such `FormData`) through the JavaScript Bridge between the webpage itself and Android (the same with iOS), but I can only send basic types.
In your case, using `FormData`, as soon it is sent to Android Java (and then to Flutter), I need to convert it into something Android can read (in this case into an array of bytes).
So, when you send it back from the `shouldInterceptFetchRequest` event, it won't convert it into `FormData`.
I need to do some more research about it.

**Comment by pichillilorenzo** [comment]
Ok, I was able to handle that case. In the next release, it should be able to recognize automatically FormData from the array of bytes.
I convert the array of bytes coming from Flutter into a string, that should be something like this:
```
------WebKitFormBoundaryT7mgmvvbhZgejkfb
Content-Disposition: form-data; name="firstname"

Foo
------WebKitFormBoundaryT7mgmvvbhZgejkfb
Content-Disposition: form-data; name="lastname"

Bar
------WebKitFormBoundaryT7mgmvvbhZgejkfb--
```
So, I test if the array of bytes converted starts with `------WebKitFormBoundary`: if `true`, it will add automatically (if not already there) the `Content-Type` header with `multipart/form-data; boundary=HERE_BOUNDARY`.
