### ISSUE TITLE
is Caching working? Why won't website load faster?

### ISSUE THREAD

**Issue by ycv005** [pichillilorenzo/flutter_inappwebview#749]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |  2.0.3   |
| Plugin version       | 5.1.0+4  |
| Android version      |    10   |
| iOS version          |               |
| Xcode version        |               |

Device information:  Realme 3 Pro

## Description

**Expected behavior:** 
Website to load fast on 2nd or 3rd or above revisit.

**Current behavior:** 
Website doesn't  load fast either 2nd, 3rd, or above revisit. I have test on my devices with good internet speed.

@pichillilorenzo  Within CrossPlatform option, since the cacheEnabled is automatically set to True, I really want to know, whether it is working or not. And if it is working, then why is taking so much time. How to test caching part? Any other way to make site load faster without hampering or breaking the website.

@tneotia Did you know any other way or solution for this ?

Note- I have good and proper Internet speed.

**Comment by tneotia** [comment]
I don't think caching is for website loading, but it is mainly used when going back to the previous site. You can tell it is working because going back is much quicker than loading it again. I could be wrong, @pichillilorenzo can answer better.

**Comment by ycv005** [comment]
@tneotia Caching is basically to make load site faster. I have read [this article](https://medium.com/@codebyamir/a-web-developers-guide-to-browser-caching-cc41f3b73e7c) or You can search elsewhere, which says-  
```
Why is Caching Important?

All browsers attempt to keep local copies of static assets in an effort to reduce page load times
and minimize network traffic.

Fetching a resource over a network will always be slower than retrieving it from local cache. 
This is true whether the server is on the same network or it’s located on the far side of the world.
```

**Comment by tneotia** [comment]
I should have been more clear - I mean it isn't used in the webview when going forward to the website, but it is used when navigating back to the previous page so it doesn't reload the content. 

E.g. initial navigation to site A does not use cache, then navigation to site B does not use cache, but going back to site A will use the cache stored for site A.

**Comment by ycv005** [comment]
@tneotia Ok, I got your point. So, I was basically look for cache system such that when a Site A has visited for the 2nd, or above time, then it should be using caching. I want to have Chome-like caching.

**Comment by pichillilorenzo** [comment]
Yes, caching is working. You can try setting `clearCache: true` and your website will take a little longer to load.
You can measure the **AVERAGE** time elapsed between the `onLoadStart` and `onLoadStop` events using the [`Stopwatch`](https://api.dart.dev/stable/2.12.2/dart-core/Stopwatch-class.html) class with and without the `clearCache: true` option.

People may get confused thinking that a WebView is a Browser (such as Chrome, Firefox, Safari, etc.). It is not.

WebView: https://www.pcmag.com/encyclopedia/term/webview
Web Browser: https://www.pcmag.com/encyclopedia/term/web-browser

You can try different configuration with the `cacheMode` Android-specific option, such as `AndroidCacheMode.LOAD_CACHE_ELSE_NETWORK` or `AndroidCacheMode.LOAD_CACHE_ONLY`, and test what best fit your use case. These are native options that offer the Android native WebView class.

Using `AndroidCacheMode.LOAD_CACHE_ONLY` will give you a load page error `net::ERR_CACHE_MISS` if there is no cache available for that website.

On Android, another way is to implement a custom cache mechanism by yourself implementing the `androidShouldInterceptRequest` Android-specific event. In order to be able to listen to this event, you need to set the `useShouldInterceptRequest` Android-specific option to `true`.

You can search online for `android webview improve cache`, `android webview custom cache mechanism`, etc. to get some hints on different ways to do that.

**Comment by ycv005** [comment]
@pichillilorenzo I have seen many place you have introduced the URI scheme instead of the string url, I think, it may also cause the speed issue. I am saying so because earlier, I have not facing any speed issue, but don't know why after few update the speed is bit slow. So, that's why I got a feeling that caching is not working.

**Comment by pichillilorenzo** [comment]
@ycv005 Nope, `Uri` type is converted to `String` when before passed to native code, just using [`Uri.toString`](https://api.dart.dev/stable/2.10.5/dart-core/Uri/toString.html) `dart:core` method. For native code, it didn't change anything.

**Comment by ycv005** [comment]
So, it may be possible that converting forward or reverse with many times may add some time complexity  ?

**Comment by pichillilorenzo** [comment]
Nope. It doesn't make any sense to me.
How much time can take to convert forward or reverse Dart type? Few milliseconds or microseconds.
For sure it won't take seconds ahahahah

**Comment by ycv005** [comment]
ok, thanks

**Comment by pichillilorenzo** [comment]
Here is a proof of that:

![Schermata 2021-03-31 alle 13 43 25](https://user-images.githubusercontent.com/5956938/113139198-1940f780-9227-11eb-88da-b719a8b26a34.png)

This is the code:
```dart
void main() {
  var stopwatch1 = Stopwatch();
  stopwatch1.start();
  var uri = Uri.parse("https://www.google.com");
  stopwatch1.stop();
  print(stopwatch1.elapsedMicroseconds);
  print(stopwatch1.elapsedMilliseconds);
  
  var stopwatch2 = Stopwatch();
  stopwatch2.start();
  var uriToString = uri.toString();
  stopwatch2.stop();
  print(stopwatch2.elapsedMicroseconds);
  print(stopwatch2.elapsedMilliseconds);
}
```

**Comment by ycv005** [comment]
What is the difference between-  AndroidCacheMode.LOAD_CACHE_ELSE_NETWORK and AndroidCacheMode.LOAD_DEFAULT ?

**Comment by pichillilorenzo** [comment]
Because they are native options, you can just search for them on the Official Android Documentation (https://developer.android.com/reference/android/webkit/WebSettings#LOAD_CACHE_ELSE_NETWORK) or using Google.

**Comment by ycv005** [comment]
@pichillilorenzo There could be a possible reason that a website load faster in chrome but slower in this webview. For ex => flipkart.com/

**Comment by tneotia** [comment]
Chrome doesn't use Android WebView exclusively under the hood I think. It likely has a lot of under-the-hood improvements. You can see this is possible clearly in apps like Brave Browser and Kiwi Browser (which I personally use and is definitely much faster than webview). You shouldn't expect Flutter webview to be a replacement for a dedicated browser especially in performance and speed.

**Comment by ycv005** [comment]
@pichillilorenzo @tneotia  Does the Headless webview and InAppWebview share the cache ? As, I was thinking to preload site in the Headless webview and when a user actually open website, then use cache to open the side in InAppWebview. If both don't share the cache, then may I achieve it.

**Comment by pichillilorenzo** [comment]
> There could be a possible reason that a website load faster in chrome but slower in this webview

As already said, you are confusing WebViews and Web Browser such as Chrome, Safari, etc. They are 2 different things.
If you want to check how Chrome works on Android, check the official code repo of Chrome [here](https://source.chromium.org/chromium/chromium/src/).
Chrome is not using Android WebView https://developer.chrome.com/docs/multidevice/webview/overview/#does-this-mean-chrome-for-android-is-using-the-webview

> Does the Headless webview and InAppWebview share the cache ? 

Android WebView cache is shared to all WebViews of your application. Headless or not, it's a WebView, so yes, it's shared.

**Comment by ycv005** [comment]
@pichillilorenzo Let say a website take 15 seconds to full load, then how much time (at maximum) it takes to load its cache into this plugins' cache manager of webview. If we have a normal internet speed.

**Comment by pichillilorenzo** [comment]
There is no answer to your question.
Every time you load a webpage, the loading time is not the same as the others. Sometimes it could take 1 second more or 1 second less.
I can't tell you how much time it could take, because this is something that depends on your app cache strategy/mechanism (custom or not) and server-side cache.

For example, using native `AndroidCacheMode.LOAD_CACHE_ONLY` option, the WebView will load all the resources of the webpage from the local cache, so it will be the fastest one. But using `AndroidCacheMode.LOAD_CACHE_ONLY` will give you a load page error `net::ERR_CACHE_MISS` if there is no cache available for that website.
So, if you need to display that webpage and you know that won't change over time or you somehow know that changes are not so frequent, you can load the first time using the default `AndroidCacheMode.LOAD_DEFAULT` and then use `AndroidCacheMode.LOAD_CACHE_ONLY` for all the other times.
Or also use a `HeadlessInAppWebView` to load it the first time using the defaul `AndroidCacheMode.LOAD_DEFAULT` and then load your `InAppWebView` widget using `AndroidCacheMode.LOAD_CACHE_ONLY`.
Or, again, implementing a custom cache mechanism by yourself through the `androidShouldInterceptRequest` Android-specific event.

**Comment by ycv005** [comment]
Great. Thanks for the info

**Comment by ycv005** [comment]
@pichillilorenzo Is there anything like Connection Time out which we used to check that loading take long time, so we as programmer can perform task like reload or anything else.

**Comment by tneotia** [comment]
You can probably do something yourself with a `Timer`, start it in `onLoadStart` and watch the time, and stop it in `onLoadStop` if the max time is not reached.

**Comment by pichillilorenzo** [comment]
> Is there anything like Connection Time out

Probably, you can use `onLoadError` for checking connection timeout errors.
On iOS, [connection timeout](https://developer.apple.com/documentation/foundation/urlerror/2293002-timedout) has error code `-1001`.
On Android, [connection timeout](https://developer.android.com/reference/android/webkit/WebViewClient#ERROR_TIMEOUT) has error code `-8`.

Also, another solution is to use the approach written by @tneotia

**Comment by phamconganh** [comment]
@pichillilorenzo I use cache in InAppWebView, but if I load a lot of requests when I turn off the app and come back without network, it loses some requests. Can I log the request when it is cached and when get it from the cache? And how to know the request from the cache and the request from the network?
