### ISSUE TITLE
How do i open url in background??

### ISSUE THREAD

**Issue by nalinnishant** [pichillilorenzo/flutter_inappwebview#760]
I want to open URL in background and then get its json content by calling a function when user clicked on a button?? how do i do this with the help of this plugin?? atleast give me some idea of how to open URL in background using this plugin?? thanks in advance

**Comment by pichillilorenzo** [comment]
You first need to intercept the button clicked and then you can make an HTTP request, for example, using the [`http`](https://pub.dev/packages/http) package.

To intercept the click on the button, you can use javascript code as you would normally do within a webpage, so adding a [javascript event listener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) for the `click` event on that specific button. If you own the page, you can change the javascript code there, otherwise you can add it calling `InAppWebViewController.evaluateJavascript` method on the `onLoadStop` event.

To send this event to the Flutter side, you should add a JavaScript Handler and call `window.flutter_inappwebview.callHandler('myHandler', buttonURL);` on the JavaScript side inside the javascript event listener callback, for example:
```javascript
var button = document.querySelector('#myButton');
button.addEventListener('click', function(event) {
  event.preventDefault(); // prevents the default event action, such as loading a new page if it's an anchor HTML element.
  var buttonURL = button.href; // if it's anchor HTML element or something else based on what kind of HTML element is.
  window.flutter_inappwebview.callHandler('myHandler', buttonURL);
});
```
On the Flutter side, you would have something like these:
```dart
child: InAppWebView(
  initialUrlRequest: URLRequest(url: Uri.parse("https://yourwebsite.com")),
  onWebViewCreated: (controller) {
    controller.addJavaScriptHandler(handlerName: 'myHandler', callback: (arguments) async {
      var url = arguments[0] as String;
      HttpClient client = new HttpClient();
      try {
        var request = await client.getUrl(Uri.parse(url));
        var response = await request.close();
        // do what you need with the response
      } catch (e) {
        print(e);
      }
    });
  },
)
```
