### ISSUE TITLE
unknown_url_scheme 

### ISSUE THREAD

**Issue by Trend74X** [pichillilorenzo/flutter_inappwebview#763]
## Description

I want to redirect to dialpad with given number when I click on telephone icon/ somewhere. My webview code is coded in angular and it redirects into dialpad when it runs in chrome, but shows error while running in inappwebview. 
I dont think its already implemented in inappwebview .

Issue it shows is
net::ERR_UNKNOWN_URL_SCHEME

**Comment by pichillilorenzo** [comment]
That's the expected behavior. You need to implement it by yourself.
People may get confused thinking that a WebView is a Browser (such as Chrome, Firefox, Safari, etc.). It is not.

WebView: https://www.pcmag.com/encyclopedia/term/webview
Web Browser: https://www.pcmag.com/encyclopedia/term/web-browser

To achieve what you need, you need to use the `shouldOverrideUrlLoading` event (to be able to listen this event, you need to enable the `useShouldOverrideUrlLoading` webview option).
Also, you can use the [url_launcher](https://pub.dev/packages/url_launcher) plugin to open the dialpad. 
Here is an example:
```dart
shouldOverrideUrlLoading: (controller, navigationAction) async {
  var uri = navigationAction.request.url!;

  if (uri.scheme == 'tel') {
    if (await canLaunch(url)) {
      // Launch the App
      await launch(
        url,
      );
      // and cancel the request
      return NavigationActionPolicy.CANCEL;
    }
  }

  return NavigationActionPolicy.ALLOW;
},
```
