### ISSUE TITLE
TargetPlatform.macOS is not yet supported by the flutter_inappwebview plugin

### ISSUE THREAD

**Issue by shmehdi01** [pichillilorenzo/flutter_inappwebview#778]
I'm using flutter_inappwebview but it is showing **TargetPlatform.macOS is not yet supported by the flutter_inappwebview** plugin when i'm running on Chrome Web.

It is working fine on Android and Ios.

![Screenshot 2021-04-02 at 3 22 33 PM](https://user-images.githubusercontent.com/36307288/113405752-eeda7000-93c7-11eb-86a6-5155b72171db.png)

**Comment by pichillilorenzo** [comment]
Well... you see that no? `TargetPlatform.macOS is not yet supported by the flutter_inappwebview` because, well, is not yet supported...

Where did you see that this plugin supports macOS??
![Schermata 2021-04-02 alle 11 59 45](https://user-images.githubusercontent.com/5956938/113405954-f17a9c80-93aa-11eb-9f3c-fb2964d2300e.png)

For desktop support, follow https://github.com/pichillilorenzo/flutter_inappwebview/issues/460

**Comment by shmehdi01** [comment]
My Bad 👍

**Comment by jyr** [comment]
> @shmehdi01 how did u resolve this?

I have the same issue 😄. I found [this](https://inappwebview.dev/blog/flutter-inappwebview-6/#macos-support), I think inappwebview 6 works, I going try

![Captura de Tela 2023-03-25 às 16 08 55](https://user-images.githubusercontent.com/59930/227744673-45620298-8abd-4524-85f5-1c06f515d3ee.png)
