### ISSUE TITLE
profiles (cookies, auth, cache, history) for webview

### ISSUE THREAD

**Issue by sandys** [pichillilorenzo/flutter_inappwebview#788]
hi,
I'm actually building a web testing tool using this library. 
I wonder if there's a way to separate multiple "profiles" for the inapp webview.

Each profile will be self contained - entire cookies, httpauth, history, cache, etc, basically everything. Chrome does have a profile folder, so is it possible to achieve something like that using this library ?

**Comment by pichillilorenzo** [comment]
No, this is not possible, otherwise, it would be already implemented/added.
Unfortunately, there are no such native official APIs to make it possible.

Only for iOS, you may try to set the `incognito:  true` WebView option, that uses the `WKWebsiteDataStore.nonPersistent()` native iOS class.
But, because of this, unfortunately, you will lose WebView data (such as cookies, cache, etc) after app restart, because non-persistent `WKWebsiteDataStore` can't be saved to disk.

Note that this is not a limitation of this plugin or any other WebView plugin but on the native WebViews of the various Operating Systems. It is simply not possible until the native Platform adds such features.

**Comment by pichillilorenzo** [comment]
Also, people may get confused thinking that a WebView is a Browser (such as Chrome, Firefox, Safari, etc.). It is not.

WebView: https://www.pcmag.com/encyclopedia/term/webview
Web Browser: https://www.pcmag.com/encyclopedia/term/web-browser

**Comment by sandys** [comment]
Thank you for replying.

I'm aware of what a webview is (I'm an android developer in the past). But
I was not sure if a webview allowed you to hook into the cookie, history,
etc this way.

I saw
https://www.theverge.com/2021/3/2/22309154/google-chrome-reading-list-new-profile-bookmarks-colors-features
, so I wondered if that was possible. Thanks for clearing it up.

**Comment by pichillilorenzo** [comment]
No problem! Thanks to you! I was just clarifying it because a lot of people think that.

Also, you should consider that the Android Chrome app is not even using the `WebView`. It uses the same render engine and JavaScript engine, but other things are written in native C code and some Java code with "bridge". So, they have access to the "full power" of the engine.
Hope Android and iOS adds support for such things! It would be very nice to have!

**Comment by sandys** [comment]
Thanks !
That makes a lot of sense.

I guess I'll have to compile chromium then :(

I was hoping to stay in Flutter ecosystem...but I guess I'll have to go
back to java.

**Comment by pichillilorenzo** [comment]
I tried once but it got a lot complicated and it was taking so much time to compile that I gave up.

**Comment by pichillilorenzo** [comment]
However, you can stay in the Flutter ecosystem but then you need to expose the chromium methods that you want to use on Flutter.

**Comment by pichillilorenzo** [comment]
Also, this could be valid only for Android.
On iOS, this won't be ever possible. Apple doesn't allow other WebViews than its native `WKWebView` to render web content.

**Comment by sandys** [comment]
Another path on this is to use a parallel space app -
https://beebom.com/best-parallel-space-alternatives/

The opensource/commercial version of this engine is this -
https://github.com/asLody/VirtualApp

**Comment by sandys** [comment]
sorry to msg on this issue, but wanted to find out if we can use a
different webview than supplied by system for your plugin ?
P.S. Android only I know.

For example, can I supply this webview as a jar file to
flutter_inappwebview ?

https://github.com/delight-im/Android-AdvancedWebView

**Comment by pichillilorenzo** [comment]
Nope, it doesn't make any sense because the WebView needs to work with the Flutter with Message Channels.
You need to implement that kind of Flutter - Android (or any other platform) 2-way communication.
In any case, what is the problem? Is there a feature missing?
