### ISSUE TITLE
Blank window when opening a specific page.

### ISSUE THREAD

**Issue by ModernChocolate** [pichillilorenzo/flutter_inappwebview#797]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     2.0.4       |
| Plugin version       |    5.3.2    |
| iOS version          |    14.4         |
| Xcode version        |      12.4         |

Device information: 

## Description

**Expected behavior:** 
[This page](https://ent.iledefrance.fr/auth/login?callback=https%3A%2F%2Fent.iledefrance.fr%2F) should load.
**Current behavior:** 
A blank page is opened instead and loading is stuck to 50%.

## Steps to reproduce

```dart
InAppWebView(
            initialUrlRequest: URLRequest(
                url: Uri.parse(
                    "https://ent.iledefrance.fr/auth/login?callback=https%3A%2F%2Fent.iledefrance.fr%2F")),
            onProgressChanged:
                (InAppWebViewController controller, int progress) {
              print(progress);
            },
 ),
```
Shell output
```
50
90
50
```

## Images   
![image](https://user-images.githubusercontent.com/45465075/114270930-4489ca80-9a0f-11eb-9269-30ba5c3eef71.png)

**Comment by pichillilorenzo** [comment]
If you check on Safari dev tools, it seems that there are some JavaScript errors and, for some reason, the page keeps refreshing itself.
I don't know what is going on on that website. This is the error you see from the console logs of Safari dev tools:
![Schermata 2021-04-11 alle 01 04 20](https://user-images.githubusercontent.com/5956938/114286765-fbaf3180-9a61-11eb-98be-c3fc968092f8.png)

It seems there is something wrong with the JavaScript of the webpage itself or something from the server-side.
It could be also a bug of `WKWebView` native class of iOS.
Try to search online on Google about: `xmlhttprequest cannot load due to access control checks`.
Unfortunately, I don't know how to help you more than this.

**Comment by ModernChocolate** [comment]
I'll check, but the Webview is correctly loaded on Android.

**Comment by pichillilorenzo** [comment]
Yes I know but it could be a problem specific to iOS only. Android is not iOS, so they have 2 different implementation of the native WebView, just like when you compare Chrome and Safari, they are not the same.
