### ISSUE TITLE
Please add cacheMode in IOSInAppWebViewOptions to work the same as in AndroidInAppWebViewOptions

### ISSUE THREAD

**Issue by misici234** [pichillilorenzo/flutter_inappwebview#814]
## Environment

**Flutter version:** 
Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-CA)
**Plugin version:**
  flutter_inappwebview: ^5.3.2
**Android version:**
4.1.3
**iOS version:**
14.4
**Xcode version:**  
12.4
**Device information:**
Apple iPhone 8

## Description
Need the offline support (web caching) in iOS to work the same as in Android. It would be great if you can add cacheMode property in IOSInAppWebViewOptions which will work the same like it works in AndroidInAppWebViewOptions.
**What you'd like to happen:** 
I'd like offline mode support in iOS to work the same as it works in Android. I was very happy to discover that just setting the following option works nice in Android
    android: AndroidInAppWebViewOptions(
      useHybridComposition: true,
      cacheMode: AndroidCacheMode.LOAD_CACHE_ELSE_NETWORK, // **NOTE**: available on Android 24+.
    ),
**Alternatives you've considered:**
Please, suggest if an alternative exists

**Comment by pichillilorenzo** [comment]
This is not possible because, well, iOS doesn't offer such a feature, otherwise I would have already done it.
However, on iOS, you can use the `iosCachePolicy` of the [`URLRequest`](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/URLRequest-class.html). It accepts the [IOSURLRequestCachePolicy](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/IOSURLRequestCachePolicy-class.html) type.

**Comment by pichillilorenzo** [comment]
If you need offline support, you can also try to use Web Archives.
